apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-php.fullname" . }}
  labels:
    app: {{ template "nginx-php.name" . }}
    chart: {{ template "nginx-php.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      targetPort: 9113
      protocol: TCP
      port: 9113
    {{- end }}
  selector:
    app: {{ template "nginx-php.name" . }}
    release: {{ .Release.Name }}
