apiVersion: v1
kind: Service
metadata:
  name: {{ template "lam.fullname" . }}
  labels:
    app: {{ template "lam.name" . }}
    chart: {{ template "lam.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "lam.name" . }}
    release: {{ .Release.Name }}
