apiVersion: v1
kind: Service
metadata:
  name: {{ template "mod-chart.fullname" . }}
  labels:
    app: {{ template "mod-chart.name" . }}
    chart: {{ template "mod-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      targetPort: 9113
      protocol: TCP
      port: 9113
    {{- end }}
  selector:
    app: {{ template "mod-chart.name" . }}
    release: {{ .Release.Name }}
